name: deploy

on:
  push:
    branches:
      - release/prd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: "14"

      - name: Installing npm modules...
        run: npm ci  # if some occured problems, try reverting to `npm install`

      - name: Decrypting secrets with gpg...
        run: |
          echo "${{ secrets.GPG_PASSPHRASE }}" | sudo gpg --batch --passphrase-fd 0 --output ".env.prd" --decrypt ".env.prd.gpg" 

      - name: Generating...
        run: npm run generate-prd

      - name: Deploying...
        run: |
          echo ""
