name: deploy

on:
  push:
    branches:
      - release/prd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - uses: actions/setup-node@v3
        with:
          node-version: 18.9.1

      - name: Installing npm modules...
        run: npm ci

      - name: Decrypting secrets with gpg...
        run: |
          echo "${{ secrets.GPG_PASSPHRASE }}" | sudo gpg --batch --passphrase-fd 0 --output "src/secrets/secret.dev.js" --decrypt "src/secrets/secret.dev.js.gpg" 
          echo "${{ secrets.GPG_PASSPHRASE }}" | sudo gpg --batch --passphrase-fd 0 --output "src/secrets/secret.prd.js" --decrypt "src/secrets/secret.prd.js.gpg" 

      - name: Generating...
        run: npm run generate

      - name: Deploying...
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Copying files to s3...
        run: |
          aws s3 sync --region ap-northeast-1 .output/public/_nuxt/ s3://xxxxx/_nuxt --cache-control "max-age=31536000"
          aws s3 sync --region ap-northeast-1 .output/public/ s3://xxxxx --cache-control "no-cache"
          aws cloudfront create-invalidation --distribution-id EXXXXXXXXXXXXX --paths "/*"
